# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Namespace
metadata:
  name: naira-testbed-mlflow
  labels:
    app.kubernetes.io/part-of: naira-testbed
    app.kubernetes.io/component: mlflow
