# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: naira-testbed-mlflow
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: naira-testbed
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
