apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mlflow
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/mlflow/mlflow.git
  timeout: 5m
  ref:
    commit: a37edf95cec2126ec1a566eb3150abed3a7b0e8e
  sparseCheckout:
    - charts
